import 'package:flutter/material.dart';
import '../../quizzes/domain/entities/quiz_entity.dart';
import '../../quizzes/services/quiz_sync_service.dart';
import '../../quizzes/infrastructure/repositories/quiz_supabase_repository.dart';
import '../../quizzes/infrastructure/local/quizzes_local_dao_shared_prefs.dart';
import '../../questions/domain/entities/question_entity.dart';
import '../../questions/services/question_sync_service.dart';
import '../../questions/infrastructure/repositories/question_supabase_repository.dart';
import '../../questions/infrastructure/local/questions_local_dao_shared_prefs.dart';
import '../../answers/domain/entities/answer_entity.dart';
import '../../answers/services/answer_sync_service.dart';
import '../../answers/infrastructure/repositories/answer_supabase_repository.dart';
import '../../answers/infrastructure/local/answers_local_dao_shared_prefs.dart';

class CreateQuizPage extends StatefulWidget {
  const CreateQuizPage({super.key});

  @override
  State<CreateQuizPage> createState() => _CreateQuizPageState();
}

// Temporary classes to hold question data before quiz is saved
class _TempQuestion {
  final String text;
  final List<_TempAnswer> answers;
  
  _TempQuestion(this.text, this.answers);
}

class _TempAnswer {
  final String text;
  final bool isCorrect;
  
  _TempAnswer(this.text, this.isCorrect);
}

class _CreateQuizPageState extends State<CreateQuizPage> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  late final QuizSyncService _quizSyncService;
  late final QuestionSyncService _questionSyncService;
  late final AnswerSyncService _answerSyncService;
  
  bool _isSaving = false;
  final List<_TempQuestion> _tempQuestions = [];

  // 🎨 Paleta de cores consistente
  static const Color _primaryBlue = Color(0xFF2563EB);
  static const Color _cardBackground = Color(0xFFF9FAFB);

  @override
  void initState() {
    super.initState();
    
    // Initialize services
    final quizDao = QuizzesLocalDaoSharedPrefs();
    final quizRepo = QuizSupabaseRepository(quizDao);
    _quizSyncService = QuizSyncService(quizRepo);
    
    final questionDao = QuestionsLocalDaoSharedPrefs();
    final questionRepo = QuestionSupabaseRepository(questionDao);
    _questionSyncService = QuestionSyncService(questionRepo);
    
    final answerDao = AnswersLocalDaoSharedPrefs();
    final answerRepo = AnswerSupabaseRepository(answerDao);
    _answerSyncService = AnswerSyncService(answerRepo);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _quizSyncService.dispose();
    _questionSyncService.dispose();
    _answerSyncService.dispose();
    super.dispose();
  }

  void _addQuestion() async {
    debugPrint('📝 Abrindo dialog de adicionar pergunta...');
    final question = await showDialog<_TempQuestion>(
      context: context,
      barrierDismissible: false, // Não fecha clicando fora
      builder: (context) {
        debugPrint('🎨 Builder do dialog executado');
        return const AddQuestionDialog();
      },
    );

    debugPrint('✅ Dialog fechado. Pergunta recebida: ${question != null}');
    if (question != null) {
      debugPrint('📊 Pergunta: "${question.text}" com ${question.answers.length} respostas');
      setState(() => _tempQuestions.add(question));
    }
  }

  Future<void> _saveQuiz() async {
    if (_titleController.text.trim().isEmpty || _tempQuestions.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Preencha o título e adicione pelo menos 1 pergunta!'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    setState(() => _isSaving = true);

    try {
      // 1. Create the quiz first (without questions)
      final quiz = QuizEntity(
        id: '', // Will be generated by Supabase
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim().isEmpty 
            ? null 
            : _descriptionController.text.trim(),
        topics: [],
        questions: [],
        isPublished: false,
      );

      final createdQuiz = await _quizSyncService.createQuiz(quiz);
      
      if (!mounted) return;

      // 2. Create questions with the quiz ID
      for (final tempQ in _tempQuestions) {
        final question = QuestionEntity(
          id: '', // Will be generated
          quizId: createdQuiz.id,
          text: tempQ.text,
          order: _tempQuestions.indexOf(tempQ),
        );

        final createdQuestion = await _questionSyncService.createQuestion(question);

        if (!mounted) return;

        // 3. Create answers for each question
        for (final tempA in tempQ.answers) {
          final answer = AnswerEntity(
            id: '', // Will be generated
            questionId: createdQuestion.id,
            text: tempA.text,
            isCorrect: tempA.isCorrect,
          );

          await _answerSyncService.createAnswer(answer);
          
          if (!mounted) return;
        }
      }

      if (!mounted) return;

      // Show success message
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Quiz criado com sucesso!'),
          backgroundColor: Colors.green,
        ),
      );

      // Wait a moment for Supabase triggers to execute
      await Future.delayed(const Duration(milliseconds: 500));

      if (!mounted) return;
      
      // Return to previous screen with true to signal refresh
      Navigator.of(context).pop(true);
    } catch (e) {
      if (!mounted) return;
      
      setState(() => _isSaving = false);
      
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Erro ao criar quiz: $e'),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _cardBackground,
      resizeToAvoidBottomInset: true,
      appBar: AppBar(
        title: const Text('Criar Quiz'),
        backgroundColor: _primaryBlue,
      ),
      body: _isSaving
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(_primaryBlue),
                  ),
                  SizedBox(height: 16),
                  Text(
                    'Salvando quiz no Supabase...',
                    style: TextStyle(fontSize: 16, color: Colors.grey),
                  ),
                ],
              ),
            )
          : Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  TextField(
                    controller: _titleController,
                    autofocus: true,
                    decoration: const InputDecoration(
                      labelText: 'Título do Quiz *',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.title, color: _primaryBlue),
                    ),
                  ),
                  const SizedBox(height: 12),
                  TextField(
                    controller: _descriptionController,
                    maxLines: 2,
                    decoration: const InputDecoration(
                      labelText: 'Descrição (opcional)',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.description, color: _primaryBlue),
                    ),
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton.icon(
                    onPressed: () {
                      debugPrint('🔘 Botão "Adicionar Pergunta" clicado');
                      _addQuestion();
                    },
                    icon: const Icon(Icons.add),
                    label: const Text('Adicionar Pergunta'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: _primaryBlue,
                      foregroundColor: Colors.white,
                      minimumSize: const Size.fromHeight(48),
                    ),
                  ),
                  const SizedBox(height: 16),
                  Expanded(
                    child: _tempQuestions.isEmpty
                        ? Center(
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Icon(
                                  Icons.question_answer_outlined,
                                  size: 64,
                                  color: Colors.grey[400],
                                ),
                                const SizedBox(height: 16),
                                Text(
                                  'Nenhuma pergunta adicionada',
                                  style: TextStyle(
                                    fontSize: 16,
                                    color: Colors.grey[600],
                                  ),
                                ),
                              ],
                            ),
                          )
                        : ListView.builder(
                            itemCount: _tempQuestions.length,
                            itemBuilder: (context, index) {
                              final q = _tempQuestions[index];
                              return Card(
                                margin: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 4,
                                ),
                                child: ListTile(
                                  leading: CircleAvatar(
                                    backgroundColor: _primaryBlue,
                                    child: Text(
                                      '${index + 1}',
                                      style: const TextStyle(color: Colors.white),
                                    ),
                                  ),
                                  title: Text(q.text),
                                  subtitle: Text('${q.answers.length} respostas'),
                                  trailing: IconButton(
                                    icon: const Icon(Icons.delete, color: Colors.red),
                                    onPressed: () {
                                      setState(() => _tempQuestions.removeAt(index));
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton.icon(
                    onPressed: _saveQuiz,
                    icon: const Icon(Icons.save),
                    label: const Text('Salvar Quiz'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.green,
                      foregroundColor: Colors.white,
                      minimumSize: const Size.fromHeight(48),
                    ),
                  ),
                ],
              ),
            ),
    );
  }
}

// ----------------- Dialog para adicionar pergunta -----------------
class AddQuestionDialog extends StatefulWidget {
  const AddQuestionDialog({super.key});

  @override
  State<AddQuestionDialog> createState() => _AddQuestionDialogState();
}

class _AddQuestionDialogState extends State<AddQuestionDialog> {
  final _questionController = TextEditingController();
  final List<_TempAnswer> _answers = [];
  final _answerController = TextEditingController();
  int? _correctIndex;

  static const Color _primaryBlue = Color(0xFF2563EB);

  void _addAnswer() {
    if (_answerController.text.trim().isEmpty) return;
    setState(() {
      _answers.add(_TempAnswer(_answerController.text.trim(), false));
      _answerController.clear();
    });
  }

  void _saveQuestion() {
    debugPrint('💾 Tentando salvar pergunta...');
    debugPrint('   Texto: "${_questionController.text.trim()}"');
    debugPrint('   Respostas: ${_answers.length}');
    debugPrint('   Índice correto: $_correctIndex');
    
    if (_questionController.text.trim().isEmpty ||
        _answers.isEmpty ||
        _correctIndex == null) {
      debugPrint('❌ Validação falhou');
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
              'Preencha a pergunta, adicione respostas e marque a correta!'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    // Mark the correct answer
    final updatedAnswers = <_TempAnswer>[];
    for (int i = 0; i < _answers.length; i++) {
      updatedAnswers.add(_TempAnswer(_answers[i].text, i == _correctIndex));
    }

    final question = _TempQuestion(_questionController.text.trim(), updatedAnswers);
    debugPrint('✅ Pergunta criada, fechando dialog');
    Navigator.of(context).pop(question);
  }

  @override
  void dispose() {
    _questionController.dispose();
    _answerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      insetPadding: const EdgeInsets.all(16),
      child: ConstrainedBox(
        constraints: BoxConstraints(
          maxHeight: MediaQuery.of(context).size.height * 0.8,
        ),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text(
                'Adicionar Pergunta',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 12),
              Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    children: [
                      TextField(
                        controller: _questionController,
                        autofocus: true,
                        maxLines: 2,
                        decoration: const InputDecoration(
                          labelText: 'Texto da Pergunta *',
                          border: OutlineInputBorder(),
                          prefixIcon: Icon(Icons.quiz, color: _primaryBlue),
                        ),
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: TextField(
                              controller: _answerController,
                              decoration: const InputDecoration(
                                labelText: 'Resposta',
                                border: OutlineInputBorder(),
                              ),
                              textInputAction: TextInputAction.done,
                              onSubmitted: (_) => _addAnswer(),
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.add_circle, color: _primaryBlue, size: 32),
                            onPressed: _addAnswer,
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      if (_answers.isEmpty)
                        Padding(
                          padding: const EdgeInsets.all(16),
                          child: Text(
                            'Adicione pelo menos 2 respostas',
                            style: TextStyle(color: Colors.grey[600]),
                          ),
                        )
                      else
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const Padding(
                              padding: EdgeInsets.all(8),
                              child: Text(
                                'Marque a resposta correta:',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                            RadioGroup<int>(
                              groupValue: _correctIndex,
                              onChanged: (val) => setState(() => _correctIndex = val),
                              child: Column(
                                children: _answers.asMap().entries.map(
                                  (entry) => Card(
                                    color: entry.key == _correctIndex
                                        ? Colors.green.withValues(alpha: 0.1)
                                        : Colors.white,
                                    child: ListTile(
                                      leading: Radio<int>(
                                        value: entry.key,
                                      ),
                                      title: Text(entry.value.text),
                                      trailing: IconButton(
                                        icon: const Icon(Icons.delete, color: Colors.red),
                                        onPressed: () {
                                          setState(() {
                                            _answers.removeAt(entry.key);
                                            if (_correctIndex == entry.key) {
                                              _correctIndex = null;
                                            } else if (_correctIndex != null &&
                                                _correctIndex! > entry.key) {
                                              _correctIndex = _correctIndex! - 1;
                                            }
                                          });
                                        },
                                      ),
                                      onTap: () =>
                                          setState(() => _correctIndex = entry.key),
                                    ),
                                  ),
                                ).toList(),
                              ),
                            ),
                          ],
                        ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 12),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Cancelar'),
                  ),
                  const SizedBox(width: 8),
                  ElevatedButton(
                    onPressed: _saveQuestion,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: _primaryBlue,
                    ),
                    child: const Text('Salvar Pergunta'),
                  ),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}


